using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace HBFC;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "HBFC.esp")
            .Run(args);
    }

    public static void RunPatch(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Patcher.Run(state, _settings.Value, Console.Error);
        Console.Error.Flush();
    }
}
